modLoader="javafml"
loaderVersion="[40,)"
license="LGPL2.1"
[[mods]]
modId="epicfight"
version = "${file.jarVersion}"
displayName="Epic Fight"
displayURL="https://github.com/TomatoPuddin/epicfightmod"
description='''
'''

[[dependencies.epicfight]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.epicfight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
